### ISSUE TITLE
Lỗi thêm hàng vào giỏ, nhưng giỏ hàng lại rỗng - Test máy redmi note 4

### ISSUE THREAD

**Issue by vuhung266** [hihahihahoho/vnshop-wap#10]
![Screenshot_2019-09-13-15-18-15-978_com vnpay bidv](https://user-images.githubusercontent.com/55273241/64848214-eb8f6000-d63a-11e9-8474-d170ae95f7e9.png)
![Screenshot_2019-09-13-15-18-46-851_com vnpay bidv](https://user-images.githubusercontent.com/55273241/64848218-ed592380-d63a-11e9-97a5-38da0bd5f847.png)

**Comment by vuhung266** [comment]
Trang giỏ hàng nên có nút "Back"

**Comment by hihahihahoho** [comment]
> Trang giỏ hàng nên có nút "Back"

Trang giỏ hàng ở samsung s10 có nút back;
bản mobile app đang dùng: agribank
![image](https://user-images.githubusercontent.com/29968144/64857467-d45a6d80-d64e-11e9-8ee0-d0f6adb15ca0.png)

**Comment by hihahihahoho** [comment]
Giỏ hàng không lỗi trên samsung s10e bản Agribank
