### ISSUE TITLE
Thêm địa chỉ giao giàng bị lỗi - test máy redmi note4

### ISSUE THREAD

**Issue by vuhung266** [hihahihahoho/vnshop-wap#12]
![Screenshot_2019-09-13-17-10-24-259_com vnpay bidv](https://user-images.githubusercontent.com/55273241/64855144-75462a00-d649-11e9-9ad5-a89ec6d360ae.png)
Điền đầy đủ thông tin và bấm vào nút thêm địa chỉ, nhưng không lưu được

**Comment by hihahihahoho** [comment]
Không xuất hiện lỗi này trên bản của agribank
