### ISSUE TITLE
Mô tả sản phẩm sơ sài

### ISSUE THREAD

**Issue by hihahihahoho** [hihahihahoho/vnshop-wap#15]
Giải pháp: format lại phần mô tả cho rõ ràng hơn, nên để show ra luon chứ không để popup
![image](https://user-images.githubusercontent.com/29968144/65017154-3f0df080-d950-11e9-9578-52f422880308.png)

**Comment by vuhung266** [comment]
Trong mục chi tiết sản phẩm nên có thêm danh sách sản phẩm cùng loại, sản phẩm cùng hãng sản xuất... để người mua có thêm lựa chọn

**Comment by vuhung266** [comment]
Nên bố sung thêm ratting cũng là cách để người mua hàng sau có thể lọc được những sản phẩm được đánh giá tốt hơn

**Comment by hihahihahoho** [comment]
> Nên bố sung thêm ratting cũng là cách để người mua hàng sau có thể lọc được những sản phẩm được đánh giá tốt hơn

Xem #16
