### ISSUE TITLE
Phần tìm kiếm trên bị lỗi

### ISSUE THREAD

**Issue by hihahihahoho** [hihahihahoho/vnshop-wap#5]
Mô tả: Khi tìm từ khóa "bỉm" không hiện ra kết quả cần tìm kiếm
Thiết bị: Samsung s10e
Phiên bản: vnshop cho agribank
![Screenshot_20190913-143657_Agribank E-Mobile Banking](https://user-images.githubusercontent.com/29968144/64845365-2f329b80-d634-11e9-87ed-050c6e97ab16.jpg)

**Comment by vuhung266** [comment]
test bằng redmi thì không gõ được tiếng Việt trong ô search

**Comment by vuhung266** [comment]
Phần dấu ( x ) để đóng tìm kiếm không chạy, đang bị cách xa chữ .
Font chữ không đồng nhất giữa các vùng
