### ISSUE TITLE
Lỗi icon không hiển thị

### ISSUE THREAD

**Issue by hihahihahoho** [hihahihahoho/vnshop-wap#7]
![Screenshot_20190913-144251_Agribank E-Mobile Banking](https://user-images.githubusercontent.com/29968144/64845618-d7e0fb00-d634-11e9-97f1-398a74f8818b.jpg)

**Comment by vuhung266** [comment]
Icon nên dùng dạng SVG để đảm bảo độ nét với dạng màn hình lớn hơn, các icon nên để đồng nhất về kích thước và không nên đề màu xám trên nền trắng như hiện tại
